name: Linux

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Setup Gyro
        uses: mattnite/setup-gyro@v1

      - name: Test
        run: gyro build test

      - name: Example (Get)
        working-directory: examples
        run: gyro build run-get

      - name: Example (Post)
        working-directory: examples
        run: gyro build run-post

      - name: Example (Download)
        working-directory: examples
        run: gyro build run-download